# Dataset yang digunakan

In [1]:
url<-"https://raw.githubusercontent.com/rii92/tugas-APG/main/28%20februari%202022/tugas%20kedua%20APG.csv"
dataset1 <- read.csv(url, sep = ",")
dataset1

x1 x2 x3
1 9  12 3 
2 2   8 4 
3 6   6 0 
4 5   4 2 
5 8  10 1

# bikin syntax no 1 dan 2

In [15]:
#buat xbar
xbar1<-mean(dataset1$x1)
xbar2<-mean(dataset1$x2)
xbar3<-mean(dataset1$x3)
xbar1
xbar2
xbar3

[1] 6

[1] 8

[1] 2

***memanfaatkan deviasi untuk mencari matrix covariance***

In [34]:
d1<-matrix(dataset1$x1)-xbar1*1
d2<-matrix(dataset1$x2)-xbar2*1
d3<-matrix(dataset1$x3)-xbar3*1
matrix(c("d1",d1,"d2",d2,"d3",d3),6,3)

[,1] [,2] [,3]
[1,] d1   d2   d3  
[2,] 3    4    1   
[3,] -4   0    2   
[4,] 0    -2   -2  
[5,] -1   -4   0   
[6,] 2    2    -1

In [30]:
n<-5
s11<-t(d1)%*%d1/(n-1)
s12<-t(d1)%*%d2/(n-1)
s13<-t(d1)%*%d3/(n-1)
s21<-t(d2)%*%d1/(n-1)
s22<-t(d2)%*%d2/(n-1)
s23<-t(d2)%*%d3/(n-1)
s31<-t(d3)%*%d1/(n-1)
s32<-t(d3)%*%d2/(n-1)
s33<-t(d3)%*%d3/(n-1)

#covarians matrix
cm1<-matrix(c(s11,s12,s13,s21,s22,s23,s31,s32,s33), 3, 3)
cm1

[,1]  [,2] [,3] 
[1,]  7.50  5.0 -1.75
[2,]  5.00 10.0  1.50
[3,] -1.75  1.5  2.50

***menggunakan S=sum(xj-x_bar)(xj-x_bar)'/(n-1) untuk mencari matrix covariance*** 

In [47]:
ss11<-sum((dataset1$x1-xbar1)*(dataset1$x1-xbar1))/(n-1)
ss12<-sum((dataset1$x1-xbar1)*(dataset1$x2-xbar2))/(n-1)
ss13<-sum((dataset1$x1-xbar1)*(dataset1$x3-xbar3))/(n-1)
ss21<-sum((dataset1$x2-xbar2)*(dataset1$x1-xbar1))/(n-1)
ss22<-sum((dataset1$x2-xbar2)*(dataset1$x2-xbar2))/(n-1)
ss23<-sum((dataset1$x2-xbar2)*(dataset1$x3-xbar3))/(n-1)
ss31<-sum((dataset1$x3-xbar3)*(dataset1$x1-xbar1))/(n-1)
ss32<-sum((dataset1$x3-xbar3)*(dataset1$x2-xbar2))/(n-1)
ss33<-sum((dataset1$x3-xbar3)*(dataset1$x3-xbar3))/(n-1)
cm2<-matrix(c(ss11,ss12,ss13,ss21,ss22,ss23,ss31,ss32,ss33),3,3)
cm2

[,1]  [,2] [,3] 
[1,]  7.50  5.0 -1.75
[2,]  5.00 10.0  1.50
[3,] -1.75  1.5  2.50

matrix S yang menggunakan cara memanfaatkan deviasi memiliki hasil yang sama dengan matrix S yang menggunakan cara penjumlahan biasa untuk mencari covariance

***Sample Correlation matrix R dengan memanfaatkan matrix S***

In [48]:
#mencari D^(-0.5)
matrixDiagonal<-matrix(c(s11^(-0.5),0,0,0,s22^(-0.5),0,0,0,s33^(-0.5)),3,3)
matrixDiagonal

[,1]      [,2]      [,3]     
[1,] 0.3651484 0.0000000 0.0000000
[2,] 0.0000000 0.3162278 0.0000000
[3,] 0.0000000 0.0000000 0.6324555

In [49]:
#matrix Correlation
mc <- matrixDiagonal%*%cm1%*%matrixDiagonal
mc

[,1]       [,2]      [,3]      
[1,]  1.0000000 0.5773503 -0.4041452
[2,]  0.5773503 1.0000000  0.3000000
[3,] -0.4041452 0.3000000  1.0000000

# Matriks correlation and covariance dengan syntax R yang sudah jadi: cov(), cor()

In [3]:
cov(dataset1)

x1    x2   x3   
x1  7.50  5.0 -1.75
x2  5.00 10.0  1.50
x3 -1.75  1.5  2.50

In [5]:
cor(dataset1)

x1         x2        x3        
x1  1.0000000 0.5773503 -0.4041452
x2  0.5773503 1.0000000  0.3000000
x3 -0.4041452 0.3000000  1.0000000

# Eigen value and eigen vector

In [6]:
eigen(cov(dataset1))


eigen() decomposition
$values
[1] 13.9049009  5.4143634  0.6807358

$vectors
             [,1]       [,2]       [,3]
[1,] -0.613679310 -0.6232975  0.4846627
[2,] -0.789496144  0.4769002 -0.3863444
[3,] -0.009671757  0.6197309  0.7847548


In [7]:
eigen(cor(dataset1))

eigen() decomposition
$values
[1] 1.591638 1.273514 0.134848

$vectors
           [,1]       [,2]       [,3]
[1,]  0.7490653 -0.2047782  0.6300533
[2,]  0.6347139  0.4943479 -0.5939347
[3,] -0.1898407  0.8447994  0.5002744
